export interface NotificationData {
  _id?: string; // MongoDB document ID (optional for frontend)
  
  // Tenant info
  tenantId: string;              // Which restaurant the notification belongs to
  tenantName?: string;           // Optional — for displaying restaurant name
  tenantDomain?: string;           // Optional — for showing logo in admin dashboard
  tenantLogo?: string;           // Optional — for showing logo in admin dashboard
  
  // Notification content
  title: string;                 // Short title (e.g. "New Order Received")
  message: string;               // Main content/description
  type: "order" | "payment" | "review" | "system" | "custom"; // Notification category
  priority?: "low" | "normal" | "high"; // For highlighting important alerts
  
  // Related entity (optional linking)
  orderId?: string;              // If related to an order
  userId?: string;               // If related to a user/customer
  createdBy?: string;            // If generated by admin/staff manually
  
  // Status tracking
  read: boolean;                 // Whether the notification has been read
  readAt?: Date;                 // When it was read
  delivered: boolean;            // Whether it has been sent to the client device
  deliveredAt?: Date;            // Delivery timestamp
  
  // Meta info
  createdAt: Date;               // Creation time
  updatedAt?: Date;              // Last update time
  url?: string;                  // Optional link to redirect user (e.g. /orders/123)
  icon?: string;                 // Optional icon for UI (e.g. "🛒" or a path)
}
